### ISSUE TITLE
Crashes when attempting to Get from empty cell

### ISSUE THREAD

**Issue by geajack** [Suppen/fishlanguage.com#1]
The instruction `g` in Fish retrieves the character at a given position in the source code. The instruction causes the interpreter to crash under certain conditions.

**Condition 1:**
**Example code:** `30g`
If you try to access a character outside of the source code area. According to the [language spec](https://esolangs.org/wiki/Fish), this should actually return a zero value. According to the spec, the codebox is "infinite in all directions", so even negative coordinates should be valid.

**Condition 2:**
**Example code:** `"A"f0pf1-0g`
Using the instruction `p`, we can insert characters into the source code. When we insert a character far away from the existing source code, the gap in between is filled with spaces. Trying to access one of these spaces with `g` crashes the interpreter.

**Comment by Suppen** [comment]
[Related](https://github.com/Suppen/fish-interpreter/issues/3), and an issue mainly with [fish-interpreter](https://github.com/Suppen/fish-interpreter), not this repo. I'll "move" this issue over there

**Comment by Suppen** [comment]
Fixed as of commit d3bed7ae32d0a841e1fd13c7d6db0779ec2663ee
