### ISSUE TITLE
Doesn't support multiple registers.

### ISSUE THREAD

**Issue by tjjfvi** [Suppen/fishlanguage.com#2]
According to the [Esolang ><> page](https://esolangs.org/wiki/fish#The_register), there is a register for each stack that is not transferred between stacks and is destroyed when the stacks are destroyed. Thus the code [`1&0[2&]&n;`](https://tio.run/##S8sszvj/31DNINpILVYtz/r/fwA), would seems like it should output `1`:
- `1` is added to the stack
- `1` is popped of the stack and put in the register
- `0` is added to the stack
- `0` is popped off the stack and a new stack is added
- `2` is added to the stack
- `2` is popped off the stack and added to the register
- The current stack is flattened onto the previous; its register is destroyed
- `1` is removed from the register and added to the stack
- `1` is popped off the stack and outputted as a number
- The execution ends.

However, on https://fishlanguage.com/, the above code errors on the final `&`, presumably because the original register was destroyed.

**Comment by Suppen** [comment]
This has now been fixed in version 0.3.3 of https://github.com/Suppen/fish-interpreter, which is now being used by https://fishlanguage.com
